### ISSUE TITLE
Blog on Monolithic vs Microservices

### ISSUE THREAD

**Issue by imgk007** [swoyam2609/Hacktober-2k22-NonTech#32]
Hi @swoyam2609 shall I create a blog based on Monolithic vs Microservices, please give me chance

**Comment by imgk007** [comment]
Hi @swoyam2609 , I have made PR regarding this blog, please check and BTW thanks for the chance :)

**Comment by priyanshu10118** [comment]
Issue resolved in PR #60 
Please merge it.
Thank You!
