### ISSUE TITLE
Design a poster for a Hackathon that would be conducted in your institute

### ISSUE THREAD

**Issue by swoyam2609** [swoyam2609/Hacktober-2k22-NonTech#5]

**Comment by aditi10701** [comment]
I am interested to work on it.

**Comment by PrinceX04** [comment]
> I am interested to work on it.

@aditi10701 Sure, You can take up the work

**Comment by aditi10701** [comment]
Will it be considered as a successful PR  under the label of hacktoberfest?

**Comment by kaal-coder** [comment]
I'm interested too. I made a video and poster today and topic is Hacktoberfest. Can I move forward @PrinceX04 ?

**Comment by PrinceX04** [comment]
> Will it be considered as a successful PR under the label of hacktoberfest?

Yes Of course

**Comment by PrinceX04** [comment]
> I'm interested too. I made a video and poster today and topic is Hacktoberfest. Can I move forward @PrinceX04 ?

@kaal-coder Yes go on.

**Comment by kaal-coder** [comment]
@PrinceX04 , Should I add them [here](https://github.com/swoyam2609/Hacktober-2k22-NonTech/tree/main/POSTERS)

**Comment by PrinceX04** [comment]
> Should I add them [here](https://github.com/swoyam2609/Hacktober-2k22-NonTech/tree/main/POSTERS)

Fork the repo. Add them in the Poster directory and create a pull request

**Comment by aditi10701** [comment]
> > Will it be considered as a successful PR under the label of hacktoberfest?
> 
> Yes Of course

I generated a pull request.

**Comment by AkanshuAich** [comment]
Plz assign me the task.

**Comment by swoyam2609** [comment]
ok @AkanshuAich 
Assigned

**Comment by RP2025** [comment]
Please assign me this task

**Comment by PrinceX04** [comment]
@RP2025 Sure Assigning it to you
