### ISSUE TITLE
Design a poster for the google event 30 DAYS OF CLOUD

### ISSUE THREAD

**Issue by swoyam2609** [swoyam2609/Hacktober-2k22-NonTech#9]

**Comment by aswinikalyan30** [comment]
Hey, can i take this up?

**Comment by PrinceX04** [comment]
@aswinikalyan30 Sure, Assigning to you.

**Comment by dp-lisin11** [comment]
assign it to me

**Comment by PrinceX04** [comment]
> assign it to me

@dp-lisin11 Sure Assigning it to you

**Comment by Bikramjit21** [comment]
Can anyone assign me this?

**Comment by PrinceX04** [comment]
@Bikramjit21 Sure Assigning it to you

**Comment by aakansha1704** [comment]
Hello @swoyam2609 @PrinceX04 ! Could I please try contributing to this as well?

**Comment by PrinceX04** [comment]
> Hello @swoyam2609 @PrinceX04 ! Could I please try contributing to this as well?

@aakansha1704 Sure Go ahead with it

**Comment by aakansha1704** [comment]
Thank you for assigning! I made a PR for the same, please let me know if any changes would be needed.
@swoyam2609 @PrinceX04
